import { create } from 'zustand';

export const DOCUMENT_TYPES = {
    ALL: 'all',
    TARIFFS: 'tariffs',
    RULES: 'rules',
    CONTRACTORS: 'contractors',
};

const mockDocuments = [
    {
        id: 'doc-1',
        type: DOCUMENT_TYPES.RULES,
        title: 'Правила пользования жилыми помещениями',
        date: '20 сентября 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '86 Kb',
    },
    {
        id: 'doc-2',
        type: DOCUMENT_TYPES.CONTRACTORS,
        title: 'Регламент работы подрядчиков',
        date: '05 октября 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '64 Kb',
    },
    {
        id: 'doc-3',
        type: DOCUMENT_TYPES.TARIFFS,
        title: 'Инструкция по паркингу',
        date: '11 августа 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '120 Kb',
    },
    {
        id: 'doc-4',
        type: DOCUMENT_TYPES.RULES,
        title: 'Памятка по обслуживанию лифтов',
        date: '02 июля 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '48 Kb',
    },
    {
        id: 'doc-5',
        type: DOCUMENT_TYPES.TARIFFS,
        title: 'График плановых начислений',
        date: '14 октября 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '52 Kb',
    },
    {
        id: 'doc-6',
        type: DOCUMENT_TYPES.CONTRACTORS,
        title: 'Отчет подрядчика по благоустройству двора',
        date: '28 июня 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '210 Kb',
    },
    {
        id: 'doc-7',
        type: DOCUMENT_TYPES.RULES,
        title: 'Правила использования общих зон',
        date: '19 сентября 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '75 Kb',
    },
    {
        id: 'doc-8',
        type: DOCUMENT_TYPES.RULES,
        title: 'Памятка для жильцов',
        date: '08 октября 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '90 Kb',
    },
    {
        id: 'doc-9',
        type: DOCUMENT_TYPES.CONTRACTORS,
        title: 'Отчет подрядчика по ремонту холла',
        date: '22 мая 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '32 Kb',
    },
    {
        id: 'doc-10',
        type: DOCUMENT_TYPES.RULES,
        title: 'Инструкция по эксплуатации домофона',
        date: '03 сентября 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '41 Kb',
    },
    {
        id: 'doc-11',
        type: DOCUMENT_TYPES.RULES,
        title: 'Изменения в правилах пользования парковкой',
        date: '12 октября 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '58 Kb',
    },
    {
        id: 'doc-12',
        type: DOCUMENT_TYPES.CONTRACTORS,
        title: 'Отчет подрядчика по установке видеокамер',
        date: '09 мая 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '135 Kb',
    },
    {
        id: 'doc-13',
        type: DOCUMENT_TYPES.CONTRACTORS,
        title: 'Регламент обслуживания инженерных систем',
        date: '26 сентября 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '170 Kb',
    },
    {
        id: 'doc-14',
        type: DOCUMENT_TYPES.TARIFFS,
        title: 'Список доступных сервисов',
        date: '01 октября 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '66 Kb',
    },
    {
        id: 'doc-15',
        type: DOCUMENT_TYPES.CONTRACTORS,
        title: 'Протокол общего собрания',
        date: '17 апреля 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '240 Kb',
    },
    {
        id: 'doc-16',
        type: DOCUMENT_TYPES.TARIFFS,
        title: 'План работ по озеленению',
        date: '07 сентября 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '98 Kb',
    },
    {
        id: 'doc-17',
        type: DOCUMENT_TYPES.RULES,
        title: 'Новые правила доступа в спортзал',
        date: '10 октября 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '72 Kb',
    },
    {
        id: 'doc-18',
        type: DOCUMENT_TYPES.CONTRACTORS,
        title: 'Отчет подрядчика по энергоаудиту',
        date: '23 марта 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '310 Kb',
    },
    {
        id: 'doc-19',
        type: DOCUMENT_TYPES.TARIFFS,
        title: 'Информация о тарифах на обслуживание дома',
        date: '29 сентября 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '82 Kb',
    },
    {
        id: 'doc-20',
        type: DOCUMENT_TYPES.CONTRACTORS,
        title: 'График работ подрядчиков',
        date: '15 октября 2026',
        fileUrl: '/assets/img/news.png',
        fileType: 'pdf',
        fileSize: '55 Kb',
    },
];

export const useDocumentsStore = create((set) => ({
    documents: mockDocuments,
    activeType: DOCUMENT_TYPES.ALL,
    setActiveType: (type) => set({ activeType: type }),
}));
