import { create } from 'zustand';

export const APPLICATION_STATUSES = {
    ALL: 'all',
    ACTIVE: 'active',
    NEW: 'new',
    CLOSED: 'closed',
};

const mockApplications = [
    {
        id: '854 541',
        name: 'Установка посудомоечной машины',
        status: APPLICATION_STATUSES.NEW,
        date: '18:45 • 26 сентября 2020',
        managerName: 'Екатерина Л.',
        managerRole: 'менеджер',
    },
    {
        id: '854 542',
        name: 'Замена лампы в коридоре',
        status: APPLICATION_STATUSES.ACTIVE,
        date: '09:20 • 27 сентября 2020',
        managerName: 'Виктор Г.',
        managerRole: 'менеджер',
    },
    {
        id: '854 543',
        name: 'Проверка счётчиков воды',
        status: APPLICATION_STATUSES.CLOSED,
        date: '14:05 • 25 сентября 2020',
        managerName: 'Марина С.',
        managerRole: 'менеджер',
    },
    {
        id: '854 544',
        name: 'Настройка домофона',
        status: APPLICATION_STATUSES.ACTIVE,
        date: '11:30 • 24 сентября 2020',
        managerName: 'Виктор Г.',
        managerRole: 'менеджер',
    },
    {
        id: '854 545',
        name: 'Замена фильтра вентиляции',
        status: APPLICATION_STATUSES.NEW,
        date: '17:10 • 28 сентября 2020',
        managerName: 'Екатерина Л.',
        managerRole: 'менеджер',
    },
    {
        id: '854 546',
        name: 'Ремонт дверного доводчика',
        status: APPLICATION_STATUSES.CLOSED,
        date: '08:55 • 21 сентября 2020',
        managerName: 'Марина С.',
        managerRole: 'менеджер',
    },
    {
        id: '854 547',
        name: 'Настройка системы видеонаблюдения',
        status: APPLICATION_STATUSES.ACTIVE,
        date: '16:40 • 23 сентября 2020',
        managerName: 'Виктор Г.',
        managerRole: 'менеджер',
    },
    {
        id: '854 548',
        name: 'Осмотр лифтового оборудования',
        status: APPLICATION_STATUSES.NEW,
        date: '10:15 • 29 сентября 2020',
        managerName: 'Екатерина Л.',
        managerRole: 'менеджер',
    },
    {
        id: '854 549',
        name: 'Регулировка отопления',
        status: APPLICATION_STATUSES.ACTIVE,
        date: '13:05 • 22 сентября 2020',
        managerName: 'Виктор Г.',
        managerRole: 'менеджер',
    },
    {
        id: '854 550',
        name: 'Ремонт розетки в подъезде',
        status: APPLICATION_STATUSES.CLOSED,
        date: '19:00 • 20 сентября 2020',
        managerName: 'Марина С.',
        managerRole: 'менеджер',
    },
    {
        id: '854 551',
        name: 'Проверка пожарной сигнализации',
        status: APPLICATION_STATUSES.NEW,
        date: '15:25 • 30 сентября 2020',
        managerName: 'Екатерина Л.',
        managerRole: 'менеджер',
    },
    {
        id: '854 552',
        name: 'Замена замка на калитке',
        status: APPLICATION_STATUSES.ACTIVE,
        date: '12:10 • 19 сентября 2020',
        managerName: 'Виктор Г.',
        managerRole: 'менеджер',
    },
    {
        id: '854 553',
        name: 'Уборка после ремонта в холле',
        status: APPLICATION_STATUSES.CLOSED,
        date: '09:45 • 18 сентября 2020',
        managerName: 'Марина С.',
        managerRole: 'менеджер',
    },
    {
        id: '854 554',
        name: 'Проверка системы доступа',
        status: APPLICATION_STATUSES.ACTIVE,
        date: '17:55 • 17 сентября 2020',
        managerName: 'Виктор Г.',
        managerRole: 'менеджер',
    },
    {
        id: '854 555',
        name: 'Обновление указателей этажей',
        status: APPLICATION_STATUSES.NEW,
        date: '08:20 • 16 сентября 2020',
        managerName: 'Екатерина Л.',
        managerRole: 'менеджер',
    },
    {
        id: '854 556',
        name: 'Ремонт кнопки вызова лифта',
        status: APPLICATION_STATUSES.CLOSED,
        date: '14:50 • 15 сентября 2020',
        managerName: 'Марина С.',
        managerRole: 'менеджер',
    },
    {
        id: '854 557',
        name: 'Проверка вентиляции в паркинге',
        status: APPLICATION_STATUSES.ACTIVE,
        date: '10:05 • 14 сентября 2020',
        managerName: 'Виктор Г.',
        managerRole: 'менеджер',
    },
    {
        id: '854 558',
        name: 'Перекраска ограждений',
        status: APPLICATION_STATUSES.NEW,
        date: '16:20 • 13 сентября 2020',
        managerName: 'Екатерина Л.',
        managerRole: 'менеджер',
    },
    {
        id: '854 559',
        name: 'Проверка освещения во дворе',
        status: APPLICATION_STATUSES.CLOSED,
        date: '11:35 • 12 сентября 2020',
        managerName: 'Марина С.',
        managerRole: 'менеджер',
    },
    {
        id: '854 560',
        name: 'Осмотр детской площадки',
        status: APPLICATION_STATUSES.ACTIVE,
        date: '09:00 • 11 сентября 2020',
        managerName: 'Виктор Г.',
        managerRole: 'менеджер',
    },
];

export const fetchMockApplications = () => Promise.resolve(mockApplications);

export const useApplicationsStore = create((set) => ({
    applications: [],
    activeStatus: APPLICATION_STATUSES.ALL,
    setActiveStatus: (status) => set({ activeStatus: status }),
    setApplications: (applications) => set({ applications }),
}));
